// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYimNLd3EJZTZDnXSGdzgOuDRX0ugz-og',
    appId: '1:753417049338:web:a620702123f29e1f9de543',
    messagingSenderId: '753417049338',
    projectId: 'instagram-clone-eac77',
    authDomain: 'instagram-clone-eac77.firebaseapp.com',
    storageBucket: 'instagram-clone-eac77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1OgmMmpvWdQ62vaLWt0yiMXnixEuOQeA',
    appId: '1:753417049338:android:bf5ceb64832989e69de543',
    messagingSenderId: '753417049338',
    projectId: 'instagram-clone-eac77',
    storageBucket: 'instagram-clone-eac77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6B3IR0gbmW9PhgSTxs_NQW4gKbuSNUu4',
    appId: '1:753417049338:ios:e965aef0950e4ead9de543',
    messagingSenderId: '753417049338',
    projectId: 'instagram-clone-eac77',
    storageBucket: 'instagram-clone-eac77.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6B3IR0gbmW9PhgSTxs_NQW4gKbuSNUu4',
    appId: '1:753417049338:ios:e965aef0950e4ead9de543',
    messagingSenderId: '753417049338',
    projectId: 'instagram-clone-eac77',
    storageBucket: 'instagram-clone-eac77.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYimNLd3EJZTZDnXSGdzgOuDRX0ugz-og',
    appId: '1:753417049338:web:65989b3e038aaed89de543',
    messagingSenderId: '753417049338',
    projectId: 'instagram-clone-eac77',
    authDomain: 'instagram-clone-eac77.firebaseapp.com',
    storageBucket: 'instagram-clone-eac77.appspot.com',
  );
}
